/**
 * Factory building a TODO list
 * @returns {todoList}
 */
module.exports = function todoList() {
    var instance = {
        /**
         * Initializes the list
         * @returns {instance}
         */
        init: function init() {
            this._ids = 0;
            this._tasks = {};
            return this;
        },

        /**
         * Gets a particular task
         * @param {String|Number} id
         * @returns {Object} Returns the task
         */
        get: function get(id) {
            return this._tasks[id];
        },

        /**
         * Add a task into the list
         * @param {String} text
         * @returns {Object} Returns the task
         */
        add: function add(text) {
            var task = {
                id: ++ this._ids, // the id is auto generated by increment
                label: text,
                checked: false
            } ;
            this._tasks[task.id] = task;
            return task;
        },

        /**
         * Removes a task
         * @param {String|Number} id
         * @returns {Object} Returns the task
         */
        remove: function remove(id) {
            var task = this.get(id);
            var tasks = this._tasks;
            var shrinked = {};
            if (task) {
                // remove the task by omitting it while cloning the list
                Object.keys(this._tasks).forEach(function(key) {
                    if (key !== id) {
                        shrinked[key] = tasks[key];
                    }
                });
                this._tasks = shrinked;
            }
            return task;
        },

        /**
         * Checks a task
         * @param {String|Number} id
         * @param {Boolean} flag
         * @returns {Object} Returns the task
         */
        check: function check(id, flag) {
            var task = this.get(id);
            if (task) {
                task.checked = !!flag;
            }
            return task;
        },

        /**
         * Gets the list of tasks
         * @returns {Array}
         */
        list: function list() {
            var tasks = this._tasks;
            return Object.keys(tasks).map(function(key) {
                return tasks[key]
            });
        }

    };

    return instance.init();
};
